# Generated by Django 4.0.6 on 2022-07-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0003_alter_link_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='link',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='link',
            name='new_url',
            field=models.CharField(blank=True, max_length=21, unique=True),
        ),
    ]
