# Generated by Django 4.0.6 on 2022-07-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0004_alter_link_managers_alter_link_new_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='new_url',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
